apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-deployment
    namespace: ai-analytics
spec:
    replicas: 3
    selector:
        matchLabels:
            app: web-app
    template:
        metadata:
            labels:
                app: web-app
        spec:
            containers:
                - name: web-container
                  image: k0va1ets/ai-analytics-web:v1
                  ports:
                      - containerPort: 5000

                  volumeMounts:
                      - name: plots-volume
                        mountPath: /app/static/plots
                        readOnly: true
                      - name: reports-volume
                        mountPath: /app/reports
                        readOnly: true

            volumes:
                - name: plots-volume
                  hostPath:
                      path: /var/lib/docker/volumes/app_plots_data/_data
                      type: Directory
                - name: reports-volume
                  hostPath:
                      path: /var/lib/docker/volumes/app_reports_data/_data
                      type: Directory
